version: "3"
services:
  container_name: backend
  build:
    context: ./
    dockerfile: Dockerfile
  volumes:
    - ./src/main/resources:/src/main/resources
  ports:
    - "5000:5000"
  restart: always